apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: auth
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: auth
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: auth
    spec:
      containers:
      - command:
        - sh
        - ./docker-entrypoint.sh
        env:
        - name: POSTGRES_DATABASE
          value: signupapp
        - name: POSTGRES_HOST
          value: postgresdb
        - name: POSTGRES_PASSWORD
          value: 123qwe
        - name: POSTGRES_USERNAME
          value: user
        image: auth
        imagePullPolicy: ""
        name: auth
        ports:
        - containerPort: 4000
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
