version: '3.4'
services:
  auth:
    build: ./backend/auth
    ports:
      - "4000:4000"
    environment:
      POSTGRES_USERNAME: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_HOST: $DB_HOST
      POSTGRES_DATABASE: $AUTH_DB
    depends_on:
      - db
    networks:
      - app-network
  web:
    build: ./web
    ports:
      - "80:80"
    depends_on:
      - auth
    networks:
      - app-network
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_DB: $AUTH_DB
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network
networks:
  app-network:
volumes:
  db-data: