version: '3.4'
services:
  postgresdb:
    hostname: postgresdb
    image: postgres:13-alpine
    container_name: postgresdb
    environment:
      POSTGRES_PASSWORD: 123qwe
      POSTGRES_USER: user
      POSTGRES_DB: signupapp
    volumes:
      - ./backend/db-data:/var/lib/postgresql/data

  adminer:
    hostname: adminer
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgresdb

  auth:
    build: ./backend/auth
    container_name: auth
    entrypoint: sh ./docker-entrypoint.sh
    ports:
      - "4000:4000"
    environment:
      POSTGRES_USERNAME: user
      POSTGRES_PASSWORD: 123qwe
      POSTGRES_HOST: postgresdb
      POSTGRES_DATABASE: signupapp
    depends_on:
      - postgresdb

  web:
    hostname: web
    container_name: web
    build: ./web
    ports:
      - "80:80"
    depends_on:
      - auth
